
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BankAccountService", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankAccountService {


    /**
     * 
     * @param amount
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ConvertEuroToMAD")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConvertEuroToMAD", targetNamespace = "http://ws/", className = "proxy.ConvertEuroToMAD")
    @ResponseWrapper(localName = "ConvertEuroToMADResponse", targetNamespace = "http://ws/", className = "proxy.ConvertEuroToMADResponse")
    @Action(input = "http://ws/BankAccountService/ConvertEuroToMADRequest", output = "http://ws/BankAccountService/ConvertEuroToMADResponse")
    public double convertEuroToMAD(
        @WebParam(name = "amount", targetNamespace = "")
        double amount);

    /**
     * 
     * @param code
     * @return
     *     returns proxy.Account
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccount", targetNamespace = "http://ws/", className = "proxy.GetAccount")
    @ResponseWrapper(localName = "getAccountResponse", targetNamespace = "http://ws/", className = "proxy.GetAccountResponse")
    @Action(input = "http://ws/BankAccountService/getAccountRequest", output = "http://ws/BankAccountService/getAccountResponse")
    public Account getAccount(
        @WebParam(name = "code", targetNamespace = "")
        int code);

    /**
     * 
     * @return
     *     returns java.util.List<proxy.Account>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAccounts", targetNamespace = "http://ws/", className = "proxy.ListAccounts")
    @ResponseWrapper(localName = "listAccountsResponse", targetNamespace = "http://ws/", className = "proxy.ListAccountsResponse")
    @Action(input = "http://ws/BankAccountService/listAccountsRequest", output = "http://ws/BankAccountService/listAccountsResponse")
    public List<Account> listAccounts();

}
