spring.application.name=digital-banking-be
spring.datasource.url=jdbc:postgresql://localhost:5432/digital_banking
spring.datasource.username=dbadmin
spring.datasource.password=dbpass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

#spring.ai.openai.api-key=${OPENAI_API_KEY}
#spring.ai.openai.chat.options.model=gpt-3.5-turbo
#telegram.bot.token=${TELEGRAM_BOT_TOKEN}